import { Platform, StyleSheet } from 'react-native'

export const ModalStepperStyle = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  modalView: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  text: {
    color: '#04444f',
    fontSize: 20,
    textAlign: 'left',
    fontFamily: 'PoppinsSemi',
    marginBottom: 10,
  },
  btn: {
    backgroundColor: '#026cd2',
    paddingHorizontal: 30,
    paddingVertical: 20,
    borderRadius: 60,
    alignItems: 'center',
    marginTop: 15,
  },
  textBtn: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'PoppinsSemi',
  },
  //Input
  count: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: '#f2f2f2',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginRight: 5,
    width: 80,
    height: 45,
    borderRadius: 51,
    textAlign: 'center',
  },
  countOrderD: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: '#f2f2f2',
    alignItems: 'center',
    justifyContent: 'space-around',
    textAlign: 'center',
    width: 300,
    height: 80,
    borderRadius: 10,
  },
  button: {
    //backgroundColor: 'pink',
    //paddingHorizontal: 20,
    //paddingVertical: 2,
    //borderRadius: 10,
    fontSize: 35,
    color: '#62c471',
    fontFamily: 'PoppinsSemi',
    marginLeft: 4,
  },
  countSelect: {
    fontSize: 30,
    color: '#04444f',
    fontFamily: 'PoppinsMedium',
    width: 100,
    textAlign: 'center',
    marginTop: 10,
  },
  button2: {
    backgroundColor: 'transparent',
    fontSize: 35,
    color: '#62c471',
    fontFamily: 'PoppinsSemi',
    textAlign: 'center',
    marginRight: 4,
  },
  //Desplegable
  product: {
    backgroundColor: 'white',
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-around',
  },
  containerDrop: {
    width: 150,
  },
  dropdown: {
    height: 60,
    width: 140,
    borderWidth: 1.5,
    borderColor: '#f2f2f2',
    borderRadius: 51,
    paddingHorizontal: 10,
  },
  placeholderStyle: {
    fontSize: 16,
    color: '#04444f',
    fontFamily: 'PoppinsMedium',
    paddingHorizontal: 10,
  },
  selectedTextStyle: {
    fontSize: 16,
    color: '#04444f',
    fontFamily: 'PoppinsMedium',
    paddingHorizontal: 10,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
})
