import { Platform, StyleSheet } from 'react-native'

export const ProductsStyle = StyleSheet.create({
  products: {
    flex: 1,
    position: 'relative',
  },
  viewCategories: {
    //position: 'absolute',
    //bottom: 10,
    //zIndex: 1,
  },
  // MAKE YOUR ORDER

  // SEARCH BAR
  containerSearch: {
    flexDirection: 'row',
    marginHorizontal: 30,
    height: 50,
    marginTop: Platform.OS === 'ios' ? 25 : null,
  },

  BgInput: {
    flex: 1,
    borderRadius: 51,
    paddingLeft: 20,
    fontSize: 16,
    color: '#04444f',
    fontFamily: 'PoppinsRegular',
    backgroundColor: '#f2f2f2',
  },
  iconSearch: {
    position: 'absolute',
    right: 20,
    top: 15,
  },
  // PRODUCT CARD
  container: {
    backgroundColor: 'white',
    marginVertical: 5,
    flexDirection: 'row',
    borderRadius: 20,
    height: 'auto',
    width: '85%',
    padding: 15,
    alignItems: 'center',
  },
  containerImage: {
    width: '35%',
    height: '100%',
  },
  ImageCardProduct: {
    flex: 1,
    width: 70,
    height: 70,
  },
  containName: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
  },
  count: {
    flexDirection: 'row',
    borderWidth: 1.5,
    borderColor: '#f2f2f2',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginRight: 5,
    width: 80,
    height: 45,
    borderRadius: 51,
    textAlign: 'center',
  },
  countOrderD: {
    flexDirection: 'row',
    //borderWidth: 1.5,
    //borderColor: '#f2f2f2',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginRight: 5,
    width: 100,
    height: 45,
    borderRadius: 51,
    textAlign: 'center',
  },
  button: {
    backgroundColor: 'transparent',
    fontSize: 25,
    color: '#62c471',
    fontFamily: 'PoppinsSemi',
    marginLeft: 4,
  },
  countSelect: {
    fontSize: 16,
    color: '#04444f',
    fontFamily: 'PoppinsMedium',
    marginLeft: 6,
    //width: 90,
    textAlign: 'center',
  },
  button2: {
    backgroundColor: 'transparent',
    fontSize: 25,
    color: '#62c471',
    fontFamily: 'PoppinsSemi',
    textAlign: 'center',
    marginRight: 4,
  },
  containerSelect: {
    flexDirection: 'row',
    marginTop: 2,
    marginRight: 10,
  },
  containerDrop: {
    width: 80,
  },
  textName: {
    color: '#04444f',
    fontSize: 15,
    width: 160,
    fontFamily: 'PoppinsMedium',
  },
  textName1: {
    color: '#868686',
    fontSize: 15,
    fontFamily: 'PoppinsRegular',
    marginTop: -5,
  },
  textPrice: {
    color: '#026cd2',
    fontFamily: 'PoppinsMedium',
    fontSize: 15,
    marginTop: -5,
  },
  quantity: {
    backgroundColor: '#026CD2',
    width: 40,
    height: 40,
    borderRadius: 10,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textQuantity: {
    fontSize: 15,
    fontFamily: 'PoppinsRegular',
    padding: 5,
    textAlign: 'center',
    color: 'white',
  },
  containerCards: { flex: 1 },
  // PRODUCT CATEGORIES
  fixedContainer: {
    flex: 1,
    marginBottom: 20,
    backgroundColor: '#026CD2',
    paddingTop: 0,
    marginTop: 0,
    paddingVertical: 5,
    paddingBottom: 10,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  textButton: {
    fontFamily: 'PoppinsSemi',
    fontSize: 14,
    color: 'white',
  },
  contenImage: {
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 15,
    margin: 5,
    padding: 15,
    alignItems: 'center',
    shadowColor: '#144D56',
    elevation: 4,
    width: 'auto',
  },
  categoriesMenu: {
    //shadowColor: '#144D56',
    //elevation: 8,
    //marginVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 15,
  },
  buttonCategory: {
    backgroundColor: '#026CD2',
    paddingVertical: 10,
    paddingHorizontal: 0,
    overflow: Platform.OS === 'ios' ? 'hidden' : null,
    borderRadius: Platform.OS === 'ios' ? 10 : 20,
    textAlign: 'center',
    fontFamily: 'PoppinsMedium',
    //shadowColor: 'black',
    //elevation: 12,
    //shadowRadius: 10,
    color: '#ffffff',
    margin: 0,
    marginVertical: Platform.OS === 'ios' ? 10 : 8,
  },
  buttonCategory2: {
    backgroundColor: '#62C471',
    paddingVertical: 10,
    paddingHorizontal: 0,
    overflow: Platform.OS === 'ios' ? 'hidden' : null,
    borderRadius: Platform.OS === 'ios' ? 24 : 50,
    textAlign: 'center',
    fontFamily: 'PoppinsMedium',
    shadowColor: 'black',
    elevation: 6,
    shadowRadius: 20,
    color: '#ffffff',
    margin: 0,
    marginVertical: Platform.OS === 'ios' ? 15 : 8,
  },
  activeCategory: {
    backgroundColor: '#62C471',
    color: 'white',
  },
  text: { color: '#04444f', textAlign: 'center', fontFamily: 'PoppinsSemi' },
  bgContinue: {
    alignItems: 'center',
    backgroundColor: '#026cd2',
    paddingHorizontal: 35,
    paddingVertical: 12,
    borderRadius: 30,
    marginTop: 20,
    width: '50%',
  },
  ContinueText: {
    color: '#ffff',
    fontWeight: 'bold',
  },
  containerButton: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 4,
  },
  // PRODUCT DETAIL

  containerDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  containSelect: {
    backgroundColor: 'white',
    borderRadius: 51,
    marginRight: 5,
    width: 100,
    height: 45,
  },

  textOrder: {
    color: '#04444f',
    fontSize: 20,
    marginBottom: 5,
  },
  rowPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 90,
  },
})
