const enTranslations = {
  home: {
    register: 'Register',
    login: 'Login',
    tandc: 'Terms & conditions',
  },
  login: {
    enterMobileNumber: 'Enter your mobile number:',
    letsBegin: "Let's Begin",
    phoneNumber: 'Phone number',
    modalTitle_1: 'We apologize',
    FirstModalmessage: "We didn't find the mobile number registered",
    FirstModalmessage2: 'Change mobile number',
    modalTitle_2: 'Hi 👋',
    secondModalMessage: '¡Please enter a phone number!',
  },
  codeOtp: {
    enterVerificationCode: 'Enter your verification code',
    codeSent: 'A 4 digit code has been sent to your phone',
    verifyAndProceed: 'Verify & Proceed',
    didntReceiveCode: "Didn't you receive the code?",
    sendAgain: 'Send again',
    title: 'Sorry',
    message: 'The code you entered is incorrect',
    code: 'Try again',
    message2Modal: 'Please enter the code.',
    waitFirstPart: 'Wait for ',
    waitSecondPart: ' seconds',
  },
  restaurants: {
    addRestaurant: 'Contact us to add a restaurant!',
  },
  suppliers: {
    addSuppliers: 'Contact us to add suppliers!',
  },
  menuPrimary: {
    Settings: 'Settings',
    orders: 'Cart',
    records: 'Records',
    chat: 'Chat',
    titleSettings: 'Settings',
    faq: 'FAQ',
    termsAndConditions: 'Terms & conditions',
    favorites: 'Favorites',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Choose your restaurant',
    suppliers: 'Suppliers',
    makeYourOrder: 'Make your order',
    orderDetail: 'Order detail',
    orderSuccessful: 'Successful order',
  },

  productSearcher: {
    placeholder: 'Search for products',
  },
  favorites2: {
    findFirstPart: 'You have ',
    findSecondPart: ' favorites products:',
  },
  categoriesMenu: {
    goBack: 'Go back',
    favorites: 'Favorites',
    continue: 'Continue',
    all: 'All',
  },
  orderDetails: {
    paymentDetails: 'Payment details',
    net: 'Net',
    tax: 'Tax',
    currentvalue: 'Current value',
    continue: 'Continue',
    title: 'Your Products',
    titleCard: "You don't have products yet",
    buttonText: 'Go to products',
  },
  deliveryDetail: {
    address: 'Address',
    deliver: 'Deliver',
    specialRequirements: 'Any special requirements?',
    continue: 'Continue',
  },
  orderSuccessful: {
    successful: 'Successful!',
    yourOrderSuccessful: 'Your order is successful',
    yourOrders: 'Your orders',
    downloadPDF: 'Download PDF',
    newOrder: 'Create new order',
  },
  record: {
    searchPlaceholder: 'Search for products',
    pastOrders: 'Past orders',
    pendingOrders: 'Pending orders',
    viewDetails: 'View details',
    order: '#Order',
    amount: 'Amount',
    date: 'Date',
    noOrders: 'No orders yet',
    bttnNoOrders: 'Order now',
    noOrdersDate: 'No orders on this date',
    openDispute: 'Open dispute',
    delivered: 'Delivered',
    pending: 'Pending',
    dispute: 'Challenged',
    settings: 'Settings',
    allOrders: 'Orders',
  },
  disputeRecord: {
    quantityDelivered: 'Enter quantity delivered:',
    quantityDefective: 'Enter quantity defective:',
    addComment: 'Add a comment:',
    sendNextOrder: 'Send Next Order',
    creditNote: 'Credit note',
    wrongQuantity: 'Wrong quantity',
    defective: 'Defective',
    other: 'Other',
    leaveYourCommentsHere: 'Leave your comments here:',
    send: 'Send',
    modalTittle: 'Successfully created dispute',
    modalText: 'Our team will verify the information',
    modalButton: 'Continue',
  },
  uploadFile: {
    customUpload: 'Add evidence',
    submitEvidence: 'Submit evidence',
    sendEmail: 'Send email with disputes',
  },
  pendingRecord: {
    products: 'Products',
    reception: 'Reception',
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
    checkYourProducts: 'Check your products',
    openDispute: 'Dispute',
    confirmOrder: 'Confirm order',
    modalTittle: 'Thank you for using',
    modalText:
      "To view your confirmed orders, go to 'Past orders' under 'Record'.",
    modalButton: 'Continue',
    modalEvidenceText:
      'The dispute will be reviewed by one of our agents and we will respond to you as soon as possible.',
    warningTitle: 'It has an open dispute',
    warningFirstPart: 'By confirming the order',
    warningSecondPart: 'the dispute will be closed ',
    warningThirdPart: 'and you confirm that everything was resolved.',
    warningConfirm: 'Confirm order',
    warningCancel: 'Cancel',
    modalMailText: 'The email with the disputes was sent to the supplier.',
  },
  stackRecord: {
    yourOrders: 'Your orders',
    orderDetails: 'Order details',
    whatWentWrong: 'What went wrong?',
    profile: 'Profile',
  },
  settings: {
    title: 'Settings',
    restaurants: 'Restaurants',
    editRestaurants: 'Edit your restaurants',
    suppliers: 'Suppliers',
    editSuppliers: 'Edit your suppliers',
    languages: 'Languages',
    english: 'English',
    spanish: 'Spanish',
    portuguese: 'Portuguese',
    faq: 'FAQ',
    termsAndConditions: 'Terms & conditions',
    logOut: 'Log out',
    customerService: 'Customer service',
  },
  pastRecord: {
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
  },
  productFind: {
    youHave: 'You have',
    foundProducts: 'found products:',
  },
  deleteProduct: {
    deleteProduct: 'Delete product',
    areYouSureToDelete: 'Are you sure to delete',
    cancel: 'Cancel',
    delete: 'Delete',
  },
  settingsFaq: {
    tittle1: 'How can ',
    tittle2: 'we help you?',
    question1: 'How do I add another restaurant?',
    question2: 'How do I add a supplier?',
    question3: 'What is Grownet?',
    question4: 'Where do I view my current orders?',
    question5: 'A received order is incomplete. What should I do?',
    answer1:
      'Contact us through our chat and let us know the name of the restaurant you want to add.',
    answer2:
      'Get in touch via our chat to add the supplier you need. Remember, we have the best suppliers for vegetables, fruits, beverages, meats, and much more.',
    answer3:
      "Discover Grownet: Your restaurant's supply solution. We make sourcing supplies a breeze, connecting you with top London market providers for fresh, high-quality products at great prices. Manage multiple restaurant locations, streamline your purchasing, and focus on what matters most – delivering a great dining experience. Join the supply management revolution with Grownet and elevate your restaurant business today!",
    answer4:
      "Go to the menu and access the 'Records' section. There, you'll find your current and previous orders. You can filter by date and view more details about all your products.",
    answer5:
      "Go to the menu and navigate to the 'Records' section. Search for the order under 'Current Orders'. You can filter by date or manually search for the order. Choose 'View details' and open a dispute for the incomplete product.",
  },
  termsAndConditions: {
    title: 'Terms and conditions of use for',
    availableDate: 'Effective Date: September',
    subtitleOne: 'Introduction',
    paragraphOne:
      'Th ese terms and conditions (hereinafter referred to as the "Terms") govern the use of the services offered by Grownet ("We, "Us," or "Our") through our mobile application and website (hereinafter referred to as the "Site"). By using our Site, you agree to these Terms and commit to abide by them.',
    subtitleTwo: 'Registration and User Account',
    paragraphTwo:
      'To utilize our services, you must register on the Site. Registration requires providing accurate and up-to-date information.',
    subtitleThree: 'Orders and Deliveries',
    paragraphThreeOne:
      'Grownet acts as an intermediary between restaurants and suppliers. Restaurants can place orders for products through our Site.',
    paragraphThreeTwo:
      'We facilitate communication between restaurants and suppliers but do not assume responsibility for the quality of products or services provided by the suppliers.',
    paragraphThreeThree:
      'Prices for products and delivery times are set by the suppliers and may be subject to change without prior notice.',
    paragraphThreeFour:
      'Deliveries will be made to the address specified in the order. Restaurants are responsible for providing an accurate address and being available to receive products at the agreed-upon time.',
    subtitleFour: 'Cancellation and Returns',
    paragraphFourOne:
      'Cancellation and return policies are subject to the policies of each supplier. We recommend reviewing the policies of each supplier before placing an order.',
    subtitleFive: 'Liability and Warranty',
    paragraphFiveOne:
      'Grownet does not assume responsibility for the products or services provided by suppliers.',
    subtitleSix: 'Privacy',
    paragraphSixOne:
      'Your privacy is important to us. Please refer to our Privacy Policy to learn how we collect, use, and protect your personal data.',
    subtitleSeven: 'Changes to the Terms',
    paragraphSevenOne:
      'Grownet reserves the right to modify these Terms at any time. Modifications will become effective as soon as they are published on the Site.',
    subtitleEight: 'Applicable Law and Jurisdiction',
    paragraphEightOne:
      'These Terms are governed by the laws of the United Kingdom, and any disputes arising in connection with these Terms will be subject to the exclusive jurisdiction of the courts of the United Kingdom.',
    subtitleNine: 'Contact',
    paragraphNineOne:
      'If you have any questions or concerns about these Terms, please contact us at ',
    paragraphNineLink: 'www.grownetapp.com',
  },
  search: {
    placeholder: 'Search your products here',
    title: 'What are you looking for?',
    text: 'Easily find what you need',
    noAvailable: 'No available products found',
    loading: 'Loading'
  },
  favorites: {
    title: 'Your Favorites',
    titleCard: "You don't have favorites yet",
    text: 'Explore products and choose your favorites by selecting the heart icon',
    buttonText: 'Go to products',
  },
  modalStepper: {
    textBtn: 'Add to Order',
  },
  cart: {
    titleCard: 'Your cart is empty',
    text: 'Explore our products and select the ones you wish to add to the cart',
    buttonText: 'Shopping list',
  },
}

export default enTranslations
